# Generated by Django 4.2.30 on 2026-06-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('blocked', 'Blocked')], default='connected', max_length=15)),
                ('device_type', models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop'), ('tv', 'TV'), ('tablet', 'Tablet'), ('gaming', 'Gaming'), ('other', 'Other')], default='other', max_length=10)),
                ('data_usage_mb', models.FloatField(default=0)),
                ('bandwidth_mbps', models.FloatField(default=0)),
                ('bandwidth_cap', models.FloatField(default=0, help_text='0 = no cap')),
                ('is_whitelisted', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, help_text='For WhatsApp alerts', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='routers.router')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
