# Generated by Django 4.2.30 on 2026-06-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_bandwidth_cap', models.PositiveIntegerField(default=100, help_text='Mbps')),
                ('qos_enabled', models.BooleanField(default=True, verbose_name='QoS (Quality of Service)')),
                ('guest_network_enabled', models.BooleanField(default=False, verbose_name='Guest Network')),
                ('auto_block_unknown', models.BooleanField(default=False, verbose_name='Auto-Block Unknown Devices')),
                ('mac_filtering_enabled', models.BooleanField(default=True, verbose_name='MAC Address Filtering')),
                ('intrusion_detection_enabled', models.BooleanField(default=True, verbose_name='Intrusion Detection')),
                ('new_device_alerts', models.BooleanField(default=True, verbose_name='New Device Alerts')),
                ('bandwidth_alerts', models.BooleanField(default=True, verbose_name='Bandwidth Alerts')),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Network Settings',
                'verbose_name_plural': 'Network Settings',
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_range', models.CharField(help_text='CIDR, e.g. 192.168.1.0/24', max_length=50)),
                ('gateway', models.GenericIPAddressField()),
                ('ips_used', models.PositiveIntegerField(default=0)),
                ('ips_total', models.PositiveIntegerField(default=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='routers.router')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BandwidthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('download_mbps', models.FloatField(default=0)),
                ('upload_mbps', models.FloatField(default=0)),
                ('total_mbps', models.FloatField(default=0)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_logs', to='routers.router')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
