# Generated by Django 4.2.30 on 2026-06-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('location_tag', models.CharField(blank=True, help_text='e.g. Nairobi - HQ', max_length=100)),
                ('router_type', models.CharField(choices=[('tp-link', 'TP-Link'), ('mikrotik', 'MikroTik'), ('cisco', 'Cisco'), ('huawei', 'Huawei'), ('ubiquiti', 'Ubiquiti'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('access_mode', models.CharField(choices=[('paid', 'Paid (subscription required)'), ('free', 'Free Access')], default='paid', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=80)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=5)),
                ('ssid', models.CharField(blank=True, max_length=100)),
                ('wlan_key', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('firmware', models.CharField(blank=True, max_length=50)),
                ('uptime', models.CharField(blank=True, help_text='e.g. 14d 6h 23m', max_length=50)),
                ('bandwidth_limit', models.PositiveIntegerField(default=200, help_text='Mbps')),
                ('current_bandwidth_usage', models.FloatField(default=0, help_text='Mbps')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('rebooting', 'Rebooting')], default='offline', max_length=10)),
                ('is_active_setup', models.BooleanField(default=False, help_text='Active Router Setup')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('syncing', 'Syncing')], default='unknown', max_length=20)),
                ('connection_error', models.TextField(blank=True)),
                ('api_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sync', 'Sync'), ('reboot', 'Reboot'), ('discover', 'Discover Devices'), ('apply_wifi', 'Apply WiFi'), ('block_mac', 'Block MAC'), ('unblock_mac', 'Unblock MAC'), ('bandwidth_limit', 'Bandwidth Limit')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='routers.router')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterMacFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('name', models.CharField(blank=True, help_text='e.g. Office Printer', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bypass_subscription', models.BooleanField(default=True, help_text='Allow access without subscription on paid routers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_filters', to='routers.router')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('router', 'mac_address')},
            },
        ),
    ]
