# Generated by Django 4.2.30 on 2026-06-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('subscription_expired', 'Subscription Expired'), ('subscription_expiring', 'Subscription Expiring Soon'), ('new_device', 'New Device'), ('bandwidth_alert', 'Bandwidth Alert'), ('intrusion', 'Intrusion Detected')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=10)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
